# Generated by Django 5.0.7 on 2024-10-25 08:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?[1-9]\\d{1,14}$"
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Категория"),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за день"
                    ),
                ),
                (
                    "available_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Доступное количество"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="inventory_images/",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RentalLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?[1-9]\\d{1,14}$"
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RentalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rental_start_date",
                    models.DateField(verbose_name="Дата начала аренды"),
                ),
                (
                    "rental_end_date",
                    models.DateField(verbose_name="Дата окончания аренды"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="Итоговая цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.customer",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.inventoryitem",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "ordering": ["-rental_start_date"],
            },
        ),
    ]
