# Generated by Django 5.0.7 on 2024-11-01 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?[1-9]\\d{1,14}$"
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RentalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rental_start_date",
                    models.DateField(verbose_name="Дата начала аренды"),
                ),
                (
                    "rental_end_date",
                    models.DateField(verbose_name="Дата окончания аренды"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="Итоговая цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "ordering": ["-rental_start_date"],
            },
        ),
    ]
