# Generated by Django 5.0.7 on 2024-11-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_panel", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalorder",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.inventoryitem",
                verbose_name="Товар",
            ),
        ),
        migrations.AddField(
            model_name="rentalorder",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.rentallocation",
                verbose_name="Магазин",
            ),
        ),
    ]
